export const data= [
    {
      id: 1,
      postedOn: new Date().getDay(),
      title: "Frontend Developer",
      type: "Full time",
      location: "Remote",
      companyName: "Google",
      companyUrl: "Google.com",
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://google.com/careers",
      logo: "https://wallpapercave.com/dwp1x/wp10268571.png",
    },
    {
      id: 2,
      postedOn: new Date().getDay(),
      title: "Backend Developer",
      type: "Part time",
      location: "Office",
      companyName: "Yahoo",
      companyUrl: "Yahoo.com",
      skills: ["Angular", " Node.js"],
      link: "https://yahoo.com/jobs",
      logo: "https://wallpapercave.com/dwp1x/wp4144449.jpg",
    },
    {
      id: 3,
      postedOn: new Date().getDay(),
      title: "Mobile dev",
      type: "Contract",
      location: "Remote",
      companyName: "Facebook",
      companyUrl: "https://facebook.com",
      skills: ["flutter"],
      link: "https://facebook.com/careers",
      logo: "https://wallpapercave.com/wp/1gxTGou.jpg",
      
    },
  ];
